INFO: Starting update from LnK data dump: 
INFO: Processing world US-11
2016-06-13 02:12:18.505
INFO: lnk lastupdate timestamp for this run 2016-06-13 02:12:18.505
INFO: update timestamp for this run 2016-06-13 02:02:57.405
INFO: update type 'full'
INFO: Beginning Data Pull...
INFO: url - http://public-data.lordsandknights.com/LKWorldServer-US-11/alliances.json.gz
INFO: total lines in data file 14880


INFO: url - http://public-data.lordsandknights.com/LKWorldServer-US-11/players.json.gz
INFO: total lines in data file 160502


INFO: url - http://public-data.lordsandknights.com/LKWorldServer-US-11/habitats.json.gz
INFO: total lines in data file 237403
Traceback (most recent call last):
  File "lnk_json_reader_all.py", line 265, in <module>
    main()
  File "lnk_json_reader_all.py", line 240, in main
    process("habitats", world, updateType)
  File "lnk_json_reader_all.py", line 196, in process
    passToDatasource(jfile, fileType)
  File "lnk_json_reader_all.py", line 136, in passToDatasource
    if fileType == "habitats" and jfile['points'] > 40: tblHabitat.writeToTable(jfile)
  File "/Users/asitm/Documents/Workspace/Projects/LakStrat/python_scripts/datasourceHabitats.py", line 119, in writeToTable
    self.insert(habitat_values)
  File "/Users/asitm/Documents/Workspace/Projects/LakStrat/python_scripts/datasourceHabitats.py", line 98, in insert
    row)
  File "/Users/asitm/Documents/Workspace/Projects/LakStrat/python_scripts/databasehelper_mysql.py", line 217, in execute
    status = c.execute(query, params)
  File "//anaconda/lib/python2.7/site-packages/pymysql/cursors.py", line 146, in execute
    result = self._query(query)
  File "//anaconda/lib/python2.7/site-packages/pymysql/cursors.py", line 296, in _query
    conn.query(q)
  File "//anaconda/lib/python2.7/site-packages/pymysql/connections.py", line 781, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "//anaconda/lib/python2.7/site-packages/pymysql/connections.py", line 942, in _read_query_result
    result.read()
  File "//anaconda/lib/python2.7/site-packages/pymysql/connections.py", line 1138, in read
    first_packet = self.connection._read_packet()
  File "//anaconda/lib/python2.7/site-packages/pymysql/connections.py", line 895, in _read_packet
    packet_header = self._read_bytes(4)
  File "//anaconda/lib/python2.7/site-packages/pymysql/connections.py", line 919, in _read_bytes
    "Lost connection to MySQL server during query (%s)" % (e,))
pymysql.err.OperationalError: (2013, 'Lost connection to MySQL server during query ([Errno 54] Connection reset by peer)')
